server:
  port: 8080

spring:
  application:
    name: spring-cloud-config-server
  # 本地储存配置
  profiles:
    active: native
  cloud:
    config:
      server:
        # 本地储存配置
        native:
          search-locations: classpath:config/
        # git储存配置
#        git:
#          uri:
#          search-paths:
#          username:
#          password: